volumes:
    dbdata:


networks:
    serverless:
        driver: bridge

services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - serverless
        environment:
            - NODE_ENV=${NODE_ENV}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DB_DATABASE=${DB_DATABASE}
        depends_on:
            - db
    db:
        image: postgres
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - dbdata:/var/lib/postgresql
        networks:
            - serverless
